name: Build NeuralEdge Engine

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build engine
      run: |
        g++ -std=c++17 -O2 main.cpp board.cpp movegen.cpp uci.cpp -o NeuralEdge
        ls -lh NeuralEdge

    - name: Upload engine artifact
      uses: actions/upload-artifact@v4
      with:
        name: NeuralEdge
        path: NeuralEdge
